services:
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    volumes:
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=ecossistema
    networks:
      - ecossistema
    expose:
      - '3307'
    ports:
      - '3307:3306'
  ecossistema:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: ecossistema
    tty: true
    volumes:
      - './:/var/www/html'
    restart: unless-stopped
    links:
      - 'mysql:mysql'
    ports:
      - '8000:8000'
      - '5173:5173'
#    command: >
#      sh -c "php artisan serve --host=0.0.0.0 --port=8000 & npm run dev-docker"
    networks:
      - ecossistema
networks:
  ecossistema:
    driver: bridge
