<?php

use App\Domain\Servico\ContOcorrencia\Execucao\Ocorrencia\Controller\CreateController;
use App\Domain\Servico\ContOcorrencia\Execucao\Ocorrencia\Controller\CreateVistoriaController;
use App\Domain\Servico\ContOcorrencia\Execucao\Ocorrencia\Controller\DeleteVistoriaImagemController;
use App\Domain\Servico\ContOcorrencia\Execucao\Ocorrencia\Controller\DeleteRegistroController;
use App\Domain\Servico\ContOcorrencia\Execucao\Ocorrencia\Controller\EnviarOcorrenciaController;
use App\Domain\Servico\ContOcorrencia\Execucao\Ocorrencia\Controller\IndexController;
use App\Domain\Servico\ContOcorrencia\Execucao\Ocorrencia\Controller\StoreController;
use App\Domain\Servico\ContOcorrencia\Execucao\Ocorrencia\Controller\StoreRegistroController;
use App\Domain\Servico\ContOcorrencia\Execucao\Ocorrencia\Controller\StoreVistoriaImagemController;
use App\Domain\Servico\ContOcorrencia\Execucao\Ocorrencia\Controller\StoreVistoriaController;
use App\Domain\Servico\ContOcorrencia\Execucao\Ocorrencia\Controller\UpdateVistoriaController;
use App\Domain\Servico\ContOcorrencia\Execucao\Ocorrencia\Controller\UpdateController;
use App\Domain\Servico\ContOcorrencia\Execucao\Ocorrencia\Controller\VisualizarRegistroController;
use App\Domain\Servico\ContOcorrencia\Execucao\Ocorrencia\Controller\VisualizarImagemVistoriaController;
use App\Domain\Servico\ContOcorrencia\Execucao\Ocorrencia\Controller\VisualizarArquivoVistoriaController;
use App\Domain\Servico\ContOcorrencia\Execucao\Ocorrencia\Controller\StoreVistoriaArquivoController;
use App\Domain\Servico\ContOcorrencia\Execucao\Ocorrencia\Controller\DeleteVistoriaArquivoController;
use Illuminate\Support\Facades\Route;

Route::get('{contrato}/{servico}/', [IndexController::class, 'index'])->name('contratos.contratada.servicos.cont_ocorrencia.execucao.ocorrencia.index');
Route::get('{contrato}/{servico}/create/{ocorrencia?}', [CreateController::class, 'index'])->name('contratos.contratada.servicos.cont_ocorrencia.execucao.ocorrencia.create');
Route::get('{contrato}/{servico}/create_vistoria/{ocorrencia}', [CreateVistoriaController::class, 'index'])->name('contratos.contratada.servicos.cont_ocorrencia.execucao.ocorrencia.create_vistoria');
Route::post('{contrato}/{servico}/store', [StoreController::class, 'index'])->name('contratos.contratada.servicos.cont_ocorrencia.execucao.ocorrencia.store');
Route::post('{contrato}/{servico}/store_registro', [StoreRegistroController::class, 'index'])->name('contratos.contratada.servicos.cont_ocorrencia.execucao.ocorrencia.store_registro');
Route::post('{contrato}/{servico}/store_vistoria', [StoreVistoriaController::class, 'index'])->name('contratos.contratada.servicos.cont_ocorrencia.execucao.ocorrencia.store_vistoria');
Route::post('{contrato}/{servico}/{ocorrencia}/store_vistoria_imagem', [StoreVistoriaImagemController::class, 'index'])->name('contratos.contratada.servicos.cont_ocorrencia.execucao.ocorrencia.store_vistoria_imagem');
Route::post('{contrato}/{servico}/{ocorrencia}/store_vistoria_arquivo', [StoreVistoriaArquivoController::class, 'index'])->name('contratos.contratada.servicos.cont_ocorrencia.execucao.ocorrencia.store_vistoria_arquivo');
Route::get('{contrato}/{servico}/visualizar_registro/{registro}', [VisualizarRegistroController::class, 'index'])->name('contratos.contratada.servicos.cont_ocorrencia.execucao.ocorrencia.visualizar_registro');
Route::post('{contrato}/{servico}/update', [UpdateController::class, 'index'])->name('contratos.contratada.servicos.cont_ocorrencia.execucao.ocorrencia.update');
Route::post('{contrato}/{servico}/update_vistoria', [UpdateVistoriaController::class, 'index'])->name('contratos.contratada.servicos.cont_ocorrencia.execucao.ocorrencia.update_vistoria');
Route::post('{contrato}/{servico}/enviar_ocorrencia', [EnviarOcorrenciaController::class, 'index'])->name('contratos.contratada.servicos.cont_ocorrencia.execucao.ocorrencia.enviar_ocorrencia');
Route::get('{contrato}/{servico}/delete/{ocorrencia}', [DeleteVistoriaImagemController::class, 'index'])->name('contratos.contratada.servicos.cont_ocorrencia.execucao.ocorrencia.delete');
Route::delete('{contrato}/{servico}/delete_registro/{registro}', [DeleteRegistroController::class, 'index'])->name('contratos.contratada.servicos.cont_ocorrencia.execucao.ocorrencia.delete_registro');
Route::delete('{contrato}/{servico}/delete_vistoria/{vistoria}', [DeleteVistoriaImagemController::class, 'index'])->name('contratos.contratada.servicos.cont_ocorrencia.execucao.ocorrencia.delete_vistoria');
Route::delete('{contrato}/{servico}/{ocorrencia}/{vistoria}/delete_vistoria_imagem/{imagem}', [DeleteVistoriaImagemController::class, 'index'])->name('contratos.contratada.servicos.cont_ocorrencia.execucao.ocorrencia.delete_vistoria_imagem');
Route::delete('{contrato}/{servico}/{ocorrencia}/{vistoria}/delete_vistoria_arquivo/{arquivo}', [DeleteVistoriaArquivoController::class, 'index'])->name('contratos.contratada.servicos.cont_ocorrencia.execucao.ocorrencia.delete_vistoria_arquivo');
Route::get('{contrato}/{servico}/{ocorrencia}/{vistoria}/visualizar_vistoria_imagem/{imagem}', [VisualizarImagemVistoriaController::class, 'index'])->name('contratos.contratada.servicos.cont_ocorrencia.execucao.ocorrencia.visualizar_vistoria_imagem');
Route::get('{contrato}/{servico}/{ocorrencia}/{vistoria}/visualizar_vistoria_arquivo/{arquivo}', [VisualizarArquivoVistoriaController::class, 'index'])->name('contratos.contratada.servicos.cont_ocorrencia.execucao.ocorrencia.visualizar_vistoria_arquivo');
