<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import NavbarContrato from '@/Pages/Sgc/Contratada/NavbarContrato.vue';
import Breadcrumb from '@/Components/Breadcrumb.vue';
import { computed, ref } from 'vue';
import * as XLSX from 'xlsx';
import { router } from '@inertiajs/vue3';

const props = defineProps({ campanha: Object, contrato: [Number, String], produto: String, contratos: Object, analises: Array });
const linhas = ref([]); const colunas = ref([]); const erro = ref(''); const previewFoto = ref(null); const showAnalysisModal = ref(false);
const status = computed(() => props.campanha.status === 'Rejeitada' ? 'Reprovada' : props.campanha.status);
const carregarPlanilha = async () => { try { const response = await fetch(props.campanha.planilha_url); const wb = XLSX.read(await response.arrayBuffer(), { type: 'array' }); const dados = XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]], { header: 1, raw: false }); colunas.value = dados[0] ?? []; linhas.value = dados.slice(1, 11); } catch { erro.value = 'Não foi possível exibir a planilha.'; } };
carregarPlanilha();
const editar = () => router.get(route('sgc.contratada.produtos.asv.edit', [props.contrato, 'asv', props.campanha.id]));
</script>

<template>
  <AuthenticatedLayout>
    <template #header><Breadcrumb :links="[{ route: route('sgc.gestao.listagem', props.contratos?.tipo_contrato), label: 'Gestão de Contratos' }, { route: route('sgc.contratada.produtos.index', [props.contrato, 'asv']), label: props.contratos?.contratada }, { route: '#', label: 'Visualizar ASV' }]" /></template>
    <NavbarContrato :tipo="{ id: props.contrato }"><template #body>
      <div class="card"><div class="card-body">
        <div v-if="analises?.length" class="alert alert-info mb-3 d-flex justify-content-between align-items-center analysis-trigger" @click="showAnalysisModal = true"><span><i class="bi bi-info-circle me-2"></i>{{ analises.length }} análise{{ analises.length !== 1 ? 's' : '' }} registrada{{ analises.length !== 1 ? 's' : '' }}</span><span class="badge bg-info text-white">Clique para visualizar</span></div>
        <div class="text-center mb-4"><h2>VISUALIZAR CAMPANHA ASV</h2><span class="badge text-white fs-6" :class="{'bg-success':campanha.status==='Aprovada','bg-danger':campanha.status==='Rejeitada','bg-warning':campanha.status==='Em análise','bg-secondary':campanha.status==='Em elaboração'}">{{ status }}</span></div>
        <div class="row g-3 mb-4"><div v-for="item in [['Campanha',campanha.id_campanha],['Empreendimento',campanha.cod_emp],['SEI DNIT',campanha.sei_dnit],['Subproduto',campanha.subproduto]]" :key="item[0]" class="col-md-3"><div class="info-box"><span>{{ item[0] }}</span><strong>{{ item[1] || 'N/A' }}</strong></div></div></div>
        <section><div class="d-flex justify-content-between align-items-center mb-2"><h4 class="section-title mb-0">Planilha</h4><a :href="campanha.planilha_url" target="_blank" class="btn btn-sm btn-outline-primary">Baixar</a></div><div v-if="erro" class="alert alert-warning">{{ erro }}</div><div v-else class="table-responsive"><table class="table table-sm table-bordered"><thead><tr><th v-for="(coluna,i) in colunas" :key="i">{{ coluna }}</th></tr></thead><tbody><tr v-for="(linha,i) in linhas" :key="i"><td v-for="(_,j) in colunas" :key="j">{{ linha[j] }}</td></tr></tbody></table></div></section>
        <section class="mt-4"><h4 class="section-title">Fotos</h4><div v-if="campanha.fotos?.length" class="photo-grid"><button v-for="foto in campanha.fotos" :key="foto.id" type="button" class="photo-card" @click="previewFoto = foto"><img v-if="foto.url" :src="foto.url" :alt="foto.nome_arquivo || 'Foto da campanha'"><div v-else class="photo-placeholder">Sem imagem</div><div class="photo-meta"><strong>{{ foto.nome_arquivo || 'Foto' }}</strong><span v-if="foto.data_captura">{{ foto.data_captura }}</span><span v-if="foto.latitude && foto.longitude">{{ foto.latitude }}, {{ foto.longitude }}</span><span v-if="foto.descricao">{{ foto.descricao }}</span></div></button></div><div v-else class="empty-state">Nenhuma foto vinculada.</div></section>
        <section class="mt-4"><h4 class="section-title">Anexos</h4><div v-if="campanha.anexos?.length" class="list-group"><a v-for="anexo in campanha.anexos" :key="anexo.id" :href="anexo.url" target="_blank" class="list-group-item list-group-item-action d-flex justify-content-between"><span>{{ anexo.nome_arquivo }}</span><span class="text-primary">Abrir</span></a></div><div v-else class="empty-state">Nenhum anexo vinculado.</div></section>
        <div v-if="['Rejeitada','Em elaboração'].includes(campanha.status)" class="text-end mt-4"><button class="btn btn-primary" @click="editar">Editar campanha</button></div>
      </div></div>
      <div v-if="showAnalysisModal" class="modal-backdrop-custom" @click.self="showAnalysisModal = false"><div class="preview-modal"><div class="d-flex justify-content-between align-items-center mb-3"><h5 class="mb-0">Histórico de análises</h5><button type="button" class="btn-close" @click="showAnalysisModal = false"></button></div><div v-for="analise in analises" :key="analise.id" class="analysis-card" :class="analise.status === 'Rejeitada' ? 'analysis-rejected' : 'analysis-approved'"><div class="d-flex justify-content-between gap-3"><strong>Versão {{ analise.versao_analise }} — {{ analise.status === 'Rejeitada' ? 'Reprovada' : analise.status }}</strong><small>{{ analise.created_at }}</small></div><small v-if="analise.fiscal?.name" class="d-block mt-1">Fiscal: {{ analise.fiscal.name }}</small><p v-if="analise.observacoes" class="mb-0 mt-2">{{ analise.observacoes }}</p></div></div></div>
      <div v-if="previewFoto" class="modal-backdrop-custom" @click.self="previewFoto = null"><div class="preview-modal"><div class="d-flex justify-content-between align-items-center mb-3"><h5 class="mb-0">{{ previewFoto.nome_arquivo || 'Foto da campanha' }}</h5><button type="button" class="btn-close" @click="previewFoto = null"></button></div><img :src="previewFoto.url" :alt="previewFoto.nome_arquivo || 'Foto da campanha'"><p v-if="previewFoto.descricao" class="mt-3 mb-0">{{ previewFoto.descricao }}</p></div></div>
    </template></NavbarContrato>
  </AuthenticatedLayout>
</template>

<style scoped>
.info-box{border:1px solid #e2e4e6;border-radius:6px;padding:12px;min-height:82px}.info-box span{display:block;color:#6c757d;font-size:.85rem;margin-bottom:6px}.info-box strong{overflow-wrap:anywhere}.section-title{font-size:1.05rem;font-weight:700;margin-bottom:12px}.analysis-trigger{cursor:pointer}.photo-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:14px}.photo-card{padding:0;text-align:left;overflow:hidden;border:1px solid #e2e4e6;border-radius:6px;background:#fff;color:inherit}.photo-card img,.photo-placeholder{width:100%;aspect-ratio:4/3;object-fit:cover;display:block;background:#f1f3f5}.photo-placeholder{display:grid;place-items:center;color:#6c757d}.photo-meta{display:flex;flex-direction:column;gap:3px;padding:10px;font-size:.8rem}.photo-meta strong{font-size:.85rem;overflow-wrap:anywhere}.empty-state{border:1px dashed #c9ced3;border-radius:6px;color:#6c757d;padding:16px;text-align:center}.analysis-card{border:1px solid;border-radius:6px;padding:12px;margin-bottom:10px}.analysis-rejected{background:#fff5f5;border-color:#f1b7b7;color:#842029}.analysis-approved{background:#f3fbf5;border-color:#b9dfc0;color:#1f6130}.modal-backdrop-custom{position:fixed;inset:0;z-index:1055;background:rgba(0,0,0,.65);display:grid;place-items:center;padding:24px}.preview-modal{width:min(900px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:8px;padding:20px}.preview-modal img{width:100%;max-height:70vh;object-fit:contain}
</style>
